Импорт библиотеки

In [54]:
import numpy as np

Объявление массивов

In [55]:
array_1 = np.arange(1,11)

In [56]:
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Размер массива:

In [57]:
array_1 = array_1.reshape(2,5)

In [58]:
array_1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [59]:
array_1.shape

(2, 5)

In [60]:
array_2 = np.random.randint(0,11,10)

In [61]:
array_3 = np.linspace(0,10,10)

In [62]:
array_4 = (np.random.randint(0,11,10))

In [63]:
print(f'Размер элемента массива в байтах: {array_1.itemsize}')
print(f'Размер элемента массива в байтах: {array_2.itemsize}')
print(f'Размер элемента массива в байтах: {array_3.itemsize}')
print(f'Размер элемента массива в байтах: {array_4.itemsize}')
print(f'Тип массива: {array_1.dtype}')
print(f'Тип массива: {array_2.dtype}')
print(f'Тип массива: {array_3.dtype}')
print(f'Тип массива: {array_4.dtype}')
print(f'Размер массива: {array_1.shape}')

Размер элемента массива в байтах: 4
Размер элемента массива в байтах: 4
Размер элемента массива в байтах: 8
Размер элемента массива в байтах: 4
Тип массива: int32
Тип массива: int32
Тип массива: float64
Тип массива: int32
Размер массива: (2, 5)


Математические вычисления:

In [64]:
array_2.sum()

54

In [65]:
np.add(array_2,array_3)

array([ 1.        ,  6.11111111, 10.22222222,  8.33333333,  9.44444444,
       11.55555556, 14.66666667, 13.77777778, 17.88888889, 11.        ])

In [66]:
np.subtract(array_2, array_3)

array([ 1.        ,  3.88888889,  5.77777778,  1.66666667,  0.55555556,
        0.44444444,  1.33333333, -1.77777778,  0.11111111, -9.        ])

In [67]:
np.multiply(array_2,array_3)

array([ 0.        ,  5.55555556, 17.77777778, 16.66666667, 22.22222222,
       33.33333333, 53.33333333, 46.66666667, 80.        , 10.        ])

In [68]:
print(f'Стандартное отклонение: {np.std(array_1)}')
print(f'Стандартное отклонение: {np.std(array_2)}')
print(f'Стандартное отклонение: {np.std(array_3)}')
print(f'Стандартное отклонение: {np.std(array_4)}')

Стандартное отклонение: 2.8722813232690143
Стандартное отклонение: 2.576819745345025
Стандартное отклонение: 3.191423692521127
Стандартное отклонение: 2.8442925306655784


Нахождение максимального число в случайном массиве:

In [69]:
max_num = array_2.max(axis=0)
print(max_num)

9


In [70]:
max_num = array_1.max(axis=0)
print(max_num)

[ 6  7  8  9 10]
