Импорт библиотеки

In [97]:
import numpy as np

Объявление массивов

In [98]:
array_1 = np.arange(1,11)

In [99]:
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Размер массива:

In [100]:
array_1 = array_1.reshape(2,5)

In [101]:
array_1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [102]:
array_1.shape

(2, 5)

In [103]:
array_2 = np.random.randint(0,11,10)

In [104]:
array_3 = np.linspace(0,10,10)

In [105]:
array_4 = (np.random.randint(0,11,10))

In [106]:
print(f'Размер элемента массива в байтах: {array_1.itemsize}')
print(f'Размер элемента массива в байтах: {array_2.itemsize}')
print(f'Размер элемента массива в байтах: {array_3.itemsize}')
print(f'Размер элемента массива в байтах: {array_4.itemsize}')
print(f'Тип массива: {array_1.dtype}')
print(f'Тип массива: {array_2.dtype}')
print(f'Тип массива: {array_3.dtype}')
print(f'Тип массива: {array_4.dtype}')
print(f'Размер массива: {array_1.shape}')

Размер элемента массива в байтах: 4
Размер элемента массива в байтах: 4
Размер элемента массива в байтах: 8
Размер элемента массива в байтах: 4
Тип массива: int32
Тип массива: int32
Тип массива: float64
Тип массива: int32
Размер массива: (2, 5)


Математические вычисления:

In [107]:
array_2.sum()

49

In [108]:
np.add(array_2,array_1)

ValueError: operands could not be broadcast together with shapes (10,) (2,5) 

In [ ]:
np.subtract(array_1, array_2)

array([-1, -4,  0,  0,  4,  6, -3,  4,  2,  2])

In [ ]:
np.multiply(array_1,array_3)

array([  0.        ,   2.22222222,   6.66666667,  13.33333333,
        22.22222222,  33.33333333,  46.66666667,  62.22222222,
        80.        , 100.        ])

In [ ]:
print(f'Стандартное отклонение: {np.std(array_1)}')
print(f'Стандартное отклонение: {np.std(array_2)}')
print(f'Стандартное отклонение: {np.std(array_3)}')
print(f'Стандартное отклонение: {np.std(array_4)}')

Стандартное отклонение: 2.8722813232690143
Стандартное отклонение: 3.0413812651491097
Стандартное отклонение: 3.191423692521127
Стандартное отклонение: 2.808914381037628


Нахождение максимального число в случайном массиве:

In [ ]:
max_num = array_2.max(axis=0)
print(max_num)

8


In [109]:
max_num = array_1.max(axis=0)
print(max_num)

[ 6  7  8  9 10]
