Импорт библиотеки

In [1]:
import numpy as np

Объявление массивов

In [2]:
array_1 = np.arange(1,11)

In [3]:
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Размер массива:

In [4]:
array_1 = array_1.reshape(2,5)

In [5]:
array_1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
array_1.shape

(2, 5)

In [7]:
array_2 = np.random.randint(0,11,10)

In [8]:
array_3 = np.linspace(0,10,10)

In [9]:
array_4 = (np.random.randint(0,11,10))

In [10]:
print(f'Размер элемента массива в байтах: {array_1.itemsize}')
print(f'Размер элемента массива в байтах: {array_2.itemsize}')
print(f'Размер элемента массива в байтах: {array_3.itemsize}')
print(f'Размер элемента массива в байтах: {array_4.itemsize}')
print(f'Тип массива: {array_1.dtype}')
print(f'Тип массива: {array_2.dtype}')
print(f'Тип массива: {array_3.dtype}')
print(f'Тип массива: {array_4.dtype}')
print(f'Размер массива: {array_1.shape}')

Размер элемента массива в байтах: 4
Размер элемента массива в байтах: 4
Размер элемента массива в байтах: 8
Размер элемента массива в байтах: 4
Тип массива: int32
Тип массива: int32
Тип массива: float64
Тип массива: int32
Размер массива: (2, 5)


Математические вычисления:

In [11]:
array_2.sum()

59

In [12]:
np.add(array_2,array_3)

array([ 9.        ,  9.11111111,  9.22222222,  8.33333333,  6.44444444,
       12.55555556,  9.66666667, 11.77777778, 18.88888889, 14.        ])

In [13]:
np.subtract(array_2, array_3)

array([ 9.        ,  6.88888889,  4.77777778,  1.66666667, -2.44444444,
        1.44444444, -3.66666667, -3.77777778,  1.11111111, -6.        ])

In [14]:
np.multiply(array_2,array_3)

array([ 0.        ,  8.88888889, 15.55555556, 16.66666667,  8.88888889,
       38.88888889, 20.        , 31.11111111, 88.88888889, 40.        ])

In [15]:
print(f'Стандартное отклонение: {np.std(array_1)}')
print(f'Стандартное отклонение: {np.std(array_2)}')
print(f'Стандартное отклонение: {np.std(array_3)}')
print(f'Стандартное отклонение: {np.std(array_4)}')

Стандартное отклонение: 2.8722813232690143
Стандартное отклонение: 2.5475478405713994
Стандартное отклонение: 3.191423692521127
Стандартное отклонение: 3.6


Нахождение максимального число в случайном массиве:

In [16]:
max_num = array_2.max(axis=0)
print(max_num)

10


In [17]:
max_num = array_1.max(axis=0)
print(max_num)

[ 6  7  8  9 10]
